### ISSUE TITLE
Codec derivation usage

### ISSUE THREAD

**Issue by tindzk** [circe/circe#1206] opened 2019-07-21 11:07 UTC
I have defined the following abstraction for my API endpoints:

```scala
case class Endpoint[In, Out](route: String)(
  implicit
    val inEncoder: io.circe.Encoder[In],
    val inDecoder: io.circe.Decoder[In],
    val outEncoder: io.circe.Encoder[Out],
    val outDecoder: io.circe.Decoder[Out]
)

case class CorrectionView(original: String, correction: String)
val correctionView =
  Endpoint[Long, Option[CorrectionView]]("/correction/view")
```

With `io.circe.generic.simple.auto._`, all four instances can be derived automatically.

I would like to use the new `Codec` functionality to shorten the compilation time. I rewrote `Endpoint` as follows:

```scala
class Endpoint[In, Out](route: String)(
  implicit
    val inCodec: io.circe.Codec[In],
    val outCodec: io.circe.Codec[Out]
)

import io.circe.generic.simple.semiauto._
val correctionView =
  Endpoint[Long, Option[CorrectionView]]("/correction/view")(deriveCodec, deriveCodec)
```

According to the pull request #1151, the fully automatic codec derivation does not support `Codec`s. Therefore, I am using `semiauto` here and pass in `deriveCodec` explicitly.

I am wondering whether there is a better way to use `Codec`s. I did try the `@JsonCodec` annotation which now uses `deriveCodec` internally, but it does not make any `Codec` instances available in the scope.

Unfortunately, my rewritten `Endpoint` does not compile because `deriveCodec` does not work for primitives:

```scala
import io.circe.generic.simple.semiauto._

implicit val longCodec   = deriveCodec[Long]
implicit val stringCodec = deriveCodec[String]
```

This yields:

```
could not find implicit value for parameter codec: io.circe.generic.simple.codec.DerivedAsObjectCodec[String]
could not find implicit value for parameter codec: io.circe.generic.simple.codec.DerivedAsObjectCodec[Long]
```

Is this the expected behaviour?

I am using the latest Circe release with Scala 2.13.0. The scalac flag `-language:experimental.macros` is enabled. The build contains the following dependencies:

```toml
scalaDeps = [
  ["io.circe", "circe-core", "0.12.0-M4"],
  ["io.circe", "circe-generic-simple", "0.12.0-M4"],
  ["io.circe", "circe-parser", "0.12.0-M4"]
]
```

**Comment by travisbrown** [comment] 2019-08-06 15:18
@tindzk Sorry for the delay in responding, but for now at least [this qualification](https://github.com/circe/circe/pull/1151) still holds:

> Note that the intention is that `Codec` should only be used to make defining instances more convenient, and not as a constraint.

This isn't set in stone, but it simplifies a lot of things.

**Comment by travisbrown** [comment] 2019-08-15 13:56
Closing for now, since this is documented and expected behavior.

**Closed by travisbrown** 2019-08-15 13:56 UTC
