### ISSUE TITLE
Embedded collection of Enumeration values causes errors in serialization of collection of objects

### ISSUE THREAD

**Issue by dzikowski** [circe/circe#386] opened 2016-09-26 10:29 UTC
I have observed weird behavior of serialization of objects with collection of Enumeration values (for example `case class User(roles: Seq[Roles.Value])`) . Serialization of collection of this objects (for example `Seq[User]`) produces JSON Object with double-colon attribute: `{"::":[obj1, obj2, ...]}`, when correct output should be JSON Array: `[obj1, obj2, ...]`. 

This error **does not** occur when instead of Enumeration values we have other objects (even with custom Encoders).

Workaround: Implement your own `Encoder` for collection of Enumeration values.

Minimal example:

``` scala
import io.circe._
import io.circe.syntax._
import io.circe.generic.auto._

object Roles extends Enumeration {
  val Admin, Guest = Value
}

implicit object RoleEncoder extends Encoder[Roles.Value] {
  override def apply(r: Roles.Value): Json = r.toString.asJson
}

case class User(roles: Seq[Roles.Value])

val u = User(Seq(Roles.Admin))

Seq(u).asJson.noSpaces
// ERROR: res0: String = {"::":[{"roles":["Admin"]}]}

implicit object RolesSeqEncoder extends Encoder[Seq[Roles.Value]] {
  override def apply(rs: Seq[Roles.Value]): Json = rs.map(_.asJson).asJson
}

Seq(u).asJson.noSpaces
// OK: res1: String = [{"roles":["Admin"]}]
```

**Comment by travisbrown** [comment] 2016-09-26 11:20
@dzikowski Hmm, that's bad. I'm taking a look now. What version of circe are you using?

**Comment by dzikowski** [comment] 2016-09-26 11:42
I have checked `0.4.1`, `0.5.1` and current head of master branch. It seems to apply to all of these versions.

**Comment by travisbrown** [comment] 2016-09-26 11:46
@dzikowski Can you tell me more about your build setup? I can't reproduce this exact error (for me no encoder is found, which is also a bug, but not as bad of one).

**Comment by dzikowski** [comment] 2016-09-26 14:04
OK. I dug a bit deeper, tried to reproduce it in isolated environment (only Circe dependencies) and... I failed :-) It seems that is error is related also with Akka HTTP and the glue I use to connect Circe with Akka HTTP. Compilation errors (no encoder found) were missing, and - I guess - in runtime some kind of default Encoder/Marshaller was chosen what led to this weird output. If you want, you can see the minimal project, where this issue is reproducible: [https://github.com/dzikowski/circe-akka-http-test](https://github.com/dzikowski/circe-akka-http-test).

I was able **sometimes** to reproduce it in the Scala Worksheet (the former code example), but not in a deterministic manner and only in the project with dependencies to Akka HTTP (perhaps I had some mess in target files or Worksheet cache).

So the issue is still compilation error, but fortunately not weird runtime behavior. Thank you for your comments!

**Comment by travisbrown** [comment] 2016-09-26 14:23
@dzikowski I've got an enumeration-less minimization:

```scala
import io.circe._
import io.circe.syntax._
import io.circe.generic.auto._

object X { case class Foo(i: Int) }

implicit val encodeFoo: Encoder[X.Foo] = Encoder[Int].contramap(_.i)

case class Foos(values: Seq[X.Foo])

List(Foos(List(X.Foo(1)))).asJson.noSpaces
// res0: String = {"::":[{"xs":[1]}]}
```

And I've tracked down the problem, although I don't have a solution yet (short of adding a Shapeless dependency to core so we can use `Lazy` in the default `Seq` encoder, which unfortunately isn't really an option).

Thanks for reporting this! It's definitely a big problem, in an area where I thought we'd worked out all the corner cases. I'll do my best to get a fix in today.

**Comment by punkratz312** [comment] 2017-06-28 08:55
Somehow the enum seems to break the derivation. Im using version 0.8.0
I've although tried to create a decoder for the enum, but that fails as well.

![image](https://user-images.githubusercontent.com/8830888/27628374-24b78a60-5bef-11e7-81da-c6bb2543d547.png)

![image](https://user-images.githubusercontent.com/8830888/27628382-2f0fc298-5bef-11e7-8c0d-6981f10ad74b.png)

**Comment by travisbrown** [comment] 2017-06-28 11:50
@punkratz312 Please post code as text instead of screen shots—it's easier to reproduce examples and to search. You will definitely need an instance for your `Enumeration` (you can create one with `Decoder.enumDecoder`, but circe doesn't provide these automatically, and circe-generic won't give them to you). If that doesn't work can you follow up with a new issue showing what you've tried? Thanks!

**Comment by travisbrown** [comment] 2019-06-11 09:54
Confirmed that this is resolved in all current Scala version on master.

**Closed by travisbrown** 2019-06-11 09:54 UTC
