### ISSUE TITLE
Line number info for decoding errors?

### ISSUE THREAD

**Issue by nornagon** [circe/circe#1464] opened 2020-05-18 16:03 UTC
With a large & complex set of JSON (or YAML), it can be difficult to figure out where a decoding error happens. The YAML parser produces line numbers for parsing errors, but the information is lost by the time a decoding error happens.

Would it be feasible to thread that information through (perhaps optionally, in order to avoid additional overhead where it's not wanted?)

**Comment by evbo** [comment] 2020-08-23 16:57
@nornagon there is a hacky way to do this, but it's not much code:

When you handle your `DecodingFailure` exceptions, reverse the `history`, which is a sequence of json nodes that brought you to the problem, and then write a recursive function that iteratively replays each item in the sequence.

So, if you failed at `Top` > `SubField1` > `SubField2`
```json
"Top": {
"SubField1" : {
  "SubField2" : "badData"
}
}
```

You could then re-load you json file, parse it, and then with the hcursor do:

```scala
def HistoryToLineNumber(cursor: ACursor, history: Seq[CursorOp]): String = {
  history.headOption match {
    // support other CursorOp subclasses...
    case Some(DownField(f)) => historyToLineNumber(cursor.downField(f), history.tail)
    case _ =>
      val target = "<Intentionally_Break_The_Json_Parser_HERE_To_Get_Line_Number!>"
      val broken = parse(
        cursor
        .withFocus(_ => Json.fromString(target))
        .top.get.toString.replace(s"""$target""", ">something that will break it!")
      )
  }
}

val errorMessageContainingLineNumber = historyToLineNumber(hcursor.downField("Top"), history.reverse)
```

Now you just do some regex extraction from the error message and you have the line number.

This is not performant, but since it will only occur on an exception, business as usual production code is not impacted

**Comment by evbo** [comment] 2020-08-23 16:58
@nornagon there is a hacky way to do this, but it's not much code:

When you handle your `DecodingFailure` exceptions, reverse the `history`, which is a sequence of json nodes that brought you to the problem, and then write a recursive function that iteratively replays each item in the sequence.

So, if you failed at `Top` > `SubField1` > `SubField2`
```json
"Top": {
"SubField1" : {
  "SubField2" : "badData"
}
}
```

You could then re-load you json file, parse it, and then with the hcursor do:

```scala
def HistoryToLineNumber(cursor: ACursor, history: Seq[CursorOp]): String = {
  history.headOption match {
    // support other CursorOp subclasses...
    case Some(DownField(f)) => historyToLineNumber(cursor.downField(f), history.tail)
    case _ =>
      val target = "<Intentionally_Break_The_Json_Parser_HERE_To_Get_Line_Number!>"
      val broken = parse(
        cursor
        .withFocus(_ => Json.fromString(target))
        .top.get.toString.replace(s""""$target"""", ">something that will break it!")
      )
  }
}

val errorMessageContainingLineNumber = historyToLineNumber(hcursor.downField("Top"), history.reverse)
```

Now you just do some regex extraction from the error message and you have the line number.

This is not performant, but since it will only occur on an exception, business as usual production code is not impacted

**Comment by evbo** [comment] 2020-08-23 17:01
@nornagon there is a hacky way to do this, but it's not much code:

When you handle your `DecodingFailure` exceptions, reverse the `history`, which is a sequence of json nodes that brought you to the problem, and then write a recursive function that iteratively replays each item in the sequence.

So, if you failed at `Top` > `SubField1` > `SubField2`
```json
"Top": {
"SubField1" : {
  "SubField2" : "badData"
}
}
```

You could then re-load you json file, parse it, and then with the hcursor do:

```scala
def HistoryToLineNumber(cursor: ACursor, history: Seq[CursorOp]): String = {
  history.headOption match {
    // support other CursorOp subclasses...
    case Some(DownField(f)) => historyToLineNumber(cursor.downField(f), history.tail)
    case _ =>
      val target = "<Intentionally_Break_The_Json_Parser_HERE_To_Get_Line_Number!>"
      val broken = parse(
        cursor
        .withFocus(_ => Json.fromString(target))
        .top.get.toString.replace(s""""$target"""", ">something that will break it!")
      )
  }
}

val errorMessageContainingLineNumber = historyToLineNumber(hcursor.downField("Top"), history.reverse)
```

Now you just do some regex extraction from the error message and you have the line number.

This is not performant, but since it will only occur on an exception, business as usual production code is not impacted.


Note: Line Numbers will only make sense if your original json file is formatted EXACTLY as circe does internally. Make sure you've already formatted your json file (e.g. using `.spaces2`).

**Comment by hamnis** [comment] 2023-07-27 09:27
Duplicate of #1412

**Closed by hamnis** 2023-07-27 09:27 UTC
