### ISSUE TITLE
Simple case class derivation doesn't work with circe 2.11 - 8

### ISSUE THREAD

**Issue by tenstriker** [circe/circe#1029] opened 2018-12-08 00:23 UTC
I know it's been asked multiple times but for me simpler example throws compile error 

```
object TestJsonLibs extends App {  
      import io.circe.generic.auto._, io.circe.syntax._
      import io.circe.parser
      import io.circe.parser._
      import io.circe.{ Decoder, Encoder }
      import io.circe.generic.semiauto._
      import io.circe.generic.semiauto.deriveDecoder

      case class Staff(name: String)
      
      implicit val kcmDecoder = deriveDecoder[Staff] //compile error
}
```

Compile error:

could not find Lazy implicit value of type io.circe.generic.decoding.DerivedDecoder[com.mypckg.TestJsonLibs.Staff]

**Comment by travisbrown** [comment] 2018-12-18 11:30
Closing since I can't reproduce this with circe 0.11.1 or either Scala 2.11 or 2.12. Feel free to open with more info, e.g.:

* What version of circe are you using?
* By "circe 2.11 - 8" do you mean "Scala 2.11.8"? 
* Can you minimize your imports?
* Can you put an explicit return type on `kcmDecoder`, since inference for implicit definitions is often buggy or weird?

**Closed by travisbrown** 2018-12-18 11:30 UTC

**Comment by tenstriker** [comment] 2018-12-18 16:42
I updated case description with versions. I tried explicit return type as well. It still fails. It's silly but its happening. I found other library that works for me. thanks for help.
