### ISSUE TITLE
Type discriminator behavior changed for 0.11.0 ?

### ISSUE THREAD

**Issue by rikardev** [circe/circe#1073] opened 2019-02-10 17:42 UTC
Hi,

First of all, loving the project, thanks!

Updating from 0.9.3 to 0.11.1 I may have found an issue with the type discriminator configuration.
I have the following class to configure my automatic derivation:

```
import io.circe.generic.extras.AutoDerivation
import io.circe.generic.extras.Configuration
import io.circe.generic.extras.decoding.{EnumerationDecoder, UnwrappedDecoder}
import io.circe.generic.extras.encoding.{EnumerationEncoder, UnwrappedEncoder}
import io.circe.{Decoder, Encoder}

object Codec {
  object auto extends AutoDerivation {   
    implicit def enumDecoder[A](implicit decoder: EnumerationDecoder[A]): Decoder[A] = decoder
    implicit def enumEncoder[A](implicit encoder: EnumerationEncoder[A]): Encoder[A] = encoder
    implicit def unwrappedDecoder[A](implicit decoder: UnwrappedDecoder[A]): Decoder[A] = decoder
    implicit def unwrappedEncoder[A](implicit encoder: UnwrappedEncoder[A]): Encoder[A] = encoder
    
    implicit val config: Configuration = Configuration.default.withDiscriminator("type")
  }
}
```
Using it on the following produces different results for different versions:
```
import io.circe.syntax._

object Test {
  sealed trait Foo
  final case class Bar(str: String) extends Foo
  final case class Baz(int: Int) extends Foo

  final case class FooObj(foo: Foo, other: String)

  def main(args: Array[String]): Unit = {

    import Codec.auto._

    val test1: Foo = Bar("test")
    val test2: Foo = Baz(123)
    val test3: FooObj = FooObj(test1, "hello")
    val test4: FooObj = FooObj(test2, "world")

    println(test1.asJson.noSpaces)
    println(test2.asJson.noSpaces)
    println(test3.asJson.noSpaces)
    println(test4.asJson.noSpaces)
  }
}
```
Having tested different versions I think something changed between 0.10.0 and 0.11.0.

0.10.0 prints
```
{"str":"test","type":"Bar"}
{"int":123,"type":"Baz"}
{"foo":{"str":"test","type":"Bar"}}
{"foo":{"int":123,"type":"Baz"}}
```
0.11.0 prints
```
{"Bar":"test"}
{"Baz":123}
{"foo":{"Bar":"test"},"other":"hello"}
{"foo":{"Baz":123},"other":"world"}
```

Have tried changing the constructor name transformer on 0.11.0 and that gets picked up so the configuration file seems to be picked up at least. 

The behavior is the same for 0.11.1

**Comment by rikardev** [comment] 2019-02-10 17:51
Just realized there's a 0.10.1 version as well. Tested that and it works the same as 0.10.0

**Comment by travisbrown** [comment] 2019-02-10 19:59
@rikardev Thanks for the complete reproduction of the issue!  The change you're seeing is because of #1023 (and #1036), which removed the `AnyVal` constraint for `UnwrappedEncoder` and `UnwrappedDecoder` instances, which means they will now be provided for any single-member case class (assuming that the member type has an instance), which means they're being used in the derivation of the instances for `Foo`  instead of the `Repr*` instances that would behave correctly with configuration.


This is potentially confusing, but "exporting" the `Unwrapped*` instances in this way isn't really standard usage in my view (I'd avoid it myself, but that's largely a matter of taste). You can recover the earlier behavior by adding the constraint to your instances:

```scala
    implicit def unwrappedDecoder[A <: AnyVal](implicit decoder: UnwrappedDecoder[A]): Decoder[A] = decoder
    implicit def unwrappedEncoder[A <: AnyVal](implicit encoder: UnwrappedEncoder[A]): Encoder[A] = encoder
```

This produces the same results on 0.11 that you previously had on 0.10.

I'm going to go ahead and close this, but feel free to re-open if the above doesn't seem right to you.

**Closed by travisbrown** 2019-02-10 19:59 UTC
