### ISSUE TITLE
Automatic Decoder derivation hangs when used across files

### ISSUE THREAD

**Issue by maxaf** [circe/circe#204] opened 2016-02-17 18:11 UTC
Took me an hour to hunt this down in a work project. The gist of it is that I have a case class for which I automatically derive `Decoder` instances using `io.circe.generic.auto`. Within this case class there is a nested field (it's a couple of levels down) that contains a field typed to an option of another case class. This last case class got turned into a sealed trait during a refactoring. At this point I could no longer compile my project: scalac simply ran forever and failed to terminate. "Forever" in this case can be defined as more than 10 minutes for a ~1,200 SLOC project.

The situation is best illustrated with a live example: https://gist.github.com/maxaf/0cf0398d16c219099ae0

Run `sbt compile` and watch it spin. I've left it for more than 10 minutes, and it never finishes. What's funny is that  dumping the contents of `model.scala` and `main.scala` into a single file & compiling that works fine. Also, `:paste`-ing the whole pile of goo into the REPL works as well!

The only conclusion I can make is that I've probably run into a scalac bug that manifests when circe is trying to automatically derive a `Decoder` for a type hierarchy housed in another file. I'm posting this here to get a second pair of eyes on the problem & make sure I'm not doing something obviously stupid.

PS: thanks for circe! It's incredibly useful and saves me a ton of time. Except when scalac fails to terminate, of course. :)

**Comment by travisbrown** [comment] 2016-03-26 01:25
Hey @maxaf, sorry this issue slipped by me (I was camping when it arrived and somehow never noticed it). Feel free to bother me on Gitter or Twitter or here if I ever just let something sit for weeks.

The good news is that I just confirmed that I can reproduce this issue in 0.3.0 and that it's fixed in 0.4.0 (not head or the snapshot, which aren't updated yet, but I'm hoping to have the release out tonight).

**Comment by maxaf** [comment] 2016-03-26 13:18
Thanks & no worries! I worked around the (still unknown to me) root cause by rearranging my compilation units. 0.4.0 looks awesome, looking forward to it!

Through a form of differential diagnosis I've pursued this issue and the general slowness of compiling any derived circe instances. The main insight was that compilation performance tanks when `target` directories are located on a slow file system. In my case this was a VirtualBox shared directory inside a Vagrant-managed VBox instance. I gained back more than 40% of compilation time by moving `target` directories to a faster file system by way of [an sbt plugin](https://github.com/maxaf/sbt-out-of-tree/blob/master/README.md).

Could you explain in a nutshell what the root cause of this issue was? I never thought that placing code in one file or another might affect anything apart from restrictions on deriving from a sealed type.

**Comment by travisbrown** [comment] 2017-06-26 02:29
This now compiles in seconds (in 0.8.0 and earlier). There are a lot of things that changed in #247 and I don't remember at the moment which pieces are most likely responsible for clearing this up, but I'm going to go ahead and close the issue since it's not a problem any more.

**Closed by travisbrown** 2017-06-26 02:29 UTC
Labels: in progress
