### ISSUE TITLE
io.circe.generic.auto._ doesn't support Option

### ISSUE THREAD

**Issue by darkfrog26** [circe/circe#586] opened 2017-03-10 01:46 UTC
Working with a case class with auto encoder/decoder support typically works fine, but if the case class contains an `Option` the auto generation doesn't work and I end up being forced to use semiauto.

**Comment by darkfrog26** [comment] 2017-03-10 02:42
As discussed on the Gitter.im channel (see history here: https://gitter.im/circe/circe/archives/2017/03/09) this seems to be an issue related to 2.12 perhaps?

For a use-case you can test with https://github.com/outr/arangodb-scala/blob/master/src/test/scala/spec/AQLSpec.scala#L16 commenting out that line of code should auto derive the case class, but it fails to do so.  It has something to do with the use of `Option` in case classes.  If you remove the `Option` entries then it will compile fine.

**Comment by travisbrown** [comment] 2017-06-26 01:20
@darkfrog26 Do you have a self-contained example? The following works for me on 2.12:

```scala
scala> import io.circe.{ Decoder, Encoder }, io.circe.generic.auto._
import io.circe.{Decoder, Encoder}
import io.circe.generic.auto._

scala> case class User(name: String,
     |                 age: Int,
     |                 _key: Option[String] = None,
     |                 _id: Option[String] = None,
     |                 _rev: Option[String] = None)
defined class User

scala> Encoder[User].apply(User("foo", 123, Some("x"), Some("y"), None))
res0: io.circe.Json =
{
  "name" : "foo",
  "age" : 123,
  "_key" : "x",
  "_id" : "y",
  "_rev" : null
}

scala> Decoder[User].decodeJson(res0)
res1: io.circe.Decoder.Result[User] = Right(User(foo,123,Some(x),Some(y),None))
```

And the second link in your second comment is broken.

**Comment by travisbrown** [comment] 2019-06-11 11:05
Closing as non-reproducible.

**Closed by travisbrown** 2019-06-11 11:05 UTC

**Comment by darkfrog26** [comment] 2019-06-11 18:35
Sorry, I never saw that you responded to this. Yeah, this is a non-issue.
