### ISSUE TITLE
Exponentially increasing compile times when using codec derivation

### ISSUE THREAD

**Issue by shado23** [circe/circe#339] opened 2016-08-05 15:31 UTC
Trying to derive a codec on the following case class leads to a compile that I killed after more than 20 minutes without having finished.

Reducing the number of values in the case class to a small number allows it to finish, but there appears to be an exponential increase in compile time when re-adding them one by one.

Auto, semiauto or macro doesn't appear to make a difference and both version 0.4.1 and 0.5.0-M2 show the same behavior (using Scala 2.11.8).

That can't be right, can it?

```
import io.circe.syntax._
import io.circe.generic.auto._

case class AssetMetadata(`IPTC:ObjectName`:                    String = "xyz",
                         `IPTC:OriginalTransmissionReference`: String = "xyz",
                         `IPTC:UniqueDocumentID`:              String = "xyz",
                         `IPTC:FixtureIdentifier`:             String = "xyz",
                         `XMP:Title`:                          String = "xyz",

                         `XMP:ImageCreatorName`:               String = "xyz",
                         `IPTC:Source`:                        String = "xyz",

                         `XMP:Creator`:                        String = "xyz",
                         `EXIF:Copyright`:                     String = "xyz",
                         `IPTC:By-line`:                       String = "xyz",
                         `IPTC:Credit`:                        String = "xyz",
                         `IPTC:CopyrightNotice`:               String = "xyz",
                         `XMP:CreditLine`:                     String = "xyz",

                         `XMP:ArtworkDateCreated`:             String = "xyz",
                         `IPTC:DateCreated`:                   String = "xyz",
                         `XMP:DateCreated`:                    String = "xyz",
                         `XMP:DateTimeDigitized`:              String = "xyz",

                         `XMP:AlternateTitleText`:             String = "xyz",
                         `XMP:ArtworkTitle`:                   String = "xyz",
                         `XMP:ArtworkCreator`:                 String = "xyz",
                         `XMP:ArtworkSource`:                  String = "xyz",

                         `IPTC:Headline`:                      String = "xyz",
                         `XMP:Headline`:                       String = "xyz",

                         `IPTC:Caption-Abstract`:              String = "xyz",
                         `XMP:Description`:                    String = "xyz",

                         `IPTC:Keywords`:                      Seq[String] = Seq("xyz"),
                         `XMP:Subject`:                        Seq[String] = Seq("xyz"),

                         `IPTC:SpecialInstructions`:           String = "xyz",
                         `XMP:Instructions`:                   String = "xyz",
                         `XMP:UsageTerms`:                     String = "xyz",
                         `XMP:Restrictions`:                   String = "xyz",

                         `XMP:Marked`:                         Boolean = true,
                         `XMP:CopyrightStatus`:                String  = "xyz",

                         `IPTC:Contact`:                       String = "xyz",
                         `XMP:CreatorWorkEmail`:               String = "xyz",
                         `XMP:CreatorWorkUrl`:                 String = "xyz",
                         `XMP:WebStatement`:                   String = "xyz")

object Application {
  def main(args: Array[String]): Unit = {
    val asset_metadata = new AssetMetadata

    println(asset_metadata.asJson)
  }
}
```

**Comment by shado23** [comment] 2016-08-08 11:27
This appears to be caused by shapeless usage, at least spray-json-shapeless has the same issue and json4s works fine.

**Comment by travisbrown** [comment] 2016-08-08 13:02
@shado23 It's not so much Shapeless usage as the difference between compile-time and runtime reflection in Scala. json4s doesn't have the same compile-time cost because what it does is entirely at runtime (which brings its own set of problems).

I'm surprised circe doesn't do better in this case, since so many of the members have the same type. I'll try to look into it asap.

**Comment by shado23** [comment] 2016-08-08 13:38
I see. That makes sense.

Thanks for looking into it.

**Comment by akovari** [comment] 2017-08-20 08:43
Is this still an issue? I seem to be having a similar issue (although I haven't confirmed it is actually the same) with 0.8.0 and scala 2.12.3, where the compilation takes pretty much until the VM dies with an OOM error. Are there other issues that could be causing an OOM and an excessive compilation times?

**Comment by travisbrown** [comment] 2019-06-11 08:55
Closing since the code above compiles more or less instantaneously on 2.12.8 and the current master.

**Closed by travisbrown** 2019-06-11 08:55 UTC
