### ISSUE TITLE
auto enc/dec not working for scalajs project, working for non scalajs project.

### ISSUE THREAD

**Issue by rkcy** [circe/circe#610] opened 2017-04-21 15:41 UTC
[clientserver.gz](https://github.com/circe/circe/files/947542/clientserver.gz)
[Circe-Sample.gz](https://github.com/circe/circe/files/947544/Circe-Sample.gz)

Non working scalajs project is clientserver.gz. 
Working project is Circe-Sample.gz
Try to compile in sbt console. CirceTest class contains the problematic code.

Github was not allowing me to upload zip file so had to change extension to gz.

**Comment by travisbrown** [comment] 2019-06-11 10:31
Closing as non-reproducible since I'm not willing to download and rename and unzip some random file from the Internet. If you can post code or a gist or some other kind of link I'm happy to take a look.

**Closed by travisbrown** 2019-06-11 10:31 UTC
