### ISSUE TITLE
Ability to explicitly declare sealed trait members

### ISSUE THREAD

**Issue by msatala** [circe/circe#221] opened 2016-03-07 14:44 UTC
This would be very useful for instances when auto codec derivation fails for sealed traits.

Project [boopickle](https://github.com/ochrons/boopickle) has this feature:

``` scala
sealed trait Fruit {
  val weight: Double
  def color: String
}

case class Banana(weight: Double) extends Fruit {
  def color = "yellow"
}

case class Kiwi(weight: Double) extends Fruit {
  def color = "brown"
}

case class Carambola(weight: Double) extends Fruit {
  def color = "yellow"
}

implicit val fruitPickler = compositePickler[Fruit].
  addConcreteType[Banana].
  addConcreteType[Kiwi].
  addConcreteType[Carambola]
```

**Comment by travisbrown** [comment] 2016-03-09 20:31
I know I could look it up, but could you describe the intended behavior of the composite codec for the record?

**Comment by msatala** [comment] 2016-08-14 17:12
Sorry for late response. The intended behavior would be that if I explicitly declare classes that extend the sealed trait, it doesn't have to be done automatically. In some cases auto codec derivation simply fails for whatever reasons. Currently the only option is to declare reader/writer manually which means a lot of unnecessary error-prone boilerplate.

**Comment by travisbrown** [comment] 2017-06-26 03:15
Closing for now—please reopen if you have a complete working example with the error.

**Closed by travisbrown** 2017-06-26 03:15 UTC
Labels: needs reproduction
