### ISSUE TITLE
inst$macro$14  is already defined as value inst$macro$14

### ISSUE THREAD

**Issue by jilen** [circe/circe#885] opened 2018-04-24 09:23 UTC
Following code generate duplicated identifer for scala 2.11.x

```scala
import io.getquill._
import io.circe.generic.auto._
import io.circe.syntax._

case class Foo(i: Int)
case class Bar(foo: Foo, j: Int)

class FooSpec(val db: FinaglePostgresContext[Literal])  {

  import db._
  val bar = Bar(Foo(1), 1)
  implicit def fooEncoder[A](implicit e: io.circe.Encoder[A]): Encoder[A] = encoder(foo => foo.asJson.noSpaces)
   quote(query[Bar].insert(lift(bar)))


}

```

[Live Demo](https://scastie.scala-lang.org/MtO8hPopRlSDhfLs7Irayw)

Note the same code just works fine for 2.12.x

Here is part the generate tree from my local machine (`inst$macro$14` seems duplicated),
note it was produced on my local machine, not scasite live example
```scala
val inst$macro$16: io.circe.generic.encoding.DerivedObjectEncoder[io.getquill.context.finagle.postgres.Bar] = {
    final class anon$importedEncoder$macro$15 extends AnyRef with _root_.scala.Serializable {
      def <init>() = {
        super.<init>();
        ()
      };
      lazy private[this] val inst$macro$14: io.circe.generic.encoding.ReprObjectEncoder[shapeless.::[Int with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("i")],Int],shapeless.HNil]] = _;
      <stable> <accessor> lazy def inst$macro$14: io.circe.generic.encoding.ReprObjectEncoder[shapeless.::[Int with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("i")],Int],shapeless.HNil]] = {
        anon$importedEncoder$macro$15.this.inst$macro$14 = ({
  final class $anon extends io.circe.generic.encoding.ReprObjectEncoder[shapeless.::[Int with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("i")],Int],shapeless.HNil]] {
    def <init>() = {
      super.<init>();
      ()
    };
    private[this] val circeGenericInstanceFori = circe.this.Encoder.encodeInt;
    final def encodeObject(a: shapeless.::[Int with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("i")],Int],shapeless.HNil]): _root_.io.circe.JsonObject = a match {
      case shapeless.::((circeGenericHListBindingFori @ _), shapeless.HNil) => io.circe.JsonObject.fromIterable(scala.collection.immutable.Vector.apply[(String, io.circe.Json)](scala.Tuple2.apply[String, io.circe.Json]("i", $anon.this.circeGenericInstanceFori.apply(circeGenericHListBindingFori))))
    }
  };
  new $anon()
}
```
The full tree is avaliable [here](https://gist.github.com/jilen/66acead73dc533449114c2c774e8c499)

**Comment by travisbrown** [comment] 2019-06-11 10:42
Closing since I'm now considering 2.11 (more or less) unsupported. If you want to post a self-contained reproduction that shows the error on the latest circe release I'm happy to take a look.

**Closed by travisbrown** 2019-06-11 10:42 UTC
